spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kwetter?serverTimezone=UTC
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
  hosts:
    - http://localhost:9093
    - http://localhost:1012
server:
  port: 8082

